name: Deploy Backend

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deployment to Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          REPO_DIR="/root/projects/backend/hrm_backend"
          REPO_URL="https://github.com/naseerai/hrm_backend.git"
          echo "=== Check repo exists ==="
          if [ ! -d "$REPO_DIR/.git" ]; then
            echo "Repo not found. Cloning..."
            mkdir -p /root/projects/backend
            cd /root/projects/backend
            git clone $REPO_URL
          else
            echo "Repo exists. Pulling latest code..."
            cd $REPO_DIR
            git pull origin main
          fi
          echo "=== Entering repo ==="
          cd $REPO_DIR
          echo "=== Copy .env.local â†’ .env ==="
          cp .env.local .env
          echo "=== Removing old container ==="
          docker compose down || true
          echo "=== Removing old image ==="
          docker images | grep "hrm_backend-main" | awk '{print $3}' | xargs -r docker rmi -f || true
          echo "=== Build new image (no cache) ==="
          docker compose build --no-cache
          echo "=== Start new container ==="
          docker compose up -d
          echo "=== DEPLOYMENT SUCCESS ==="
