name: Deploy Backend

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          REPO_DIR="/root/projects/backend/hrm_backend"
          REPO_URL="git@github.com:naseerai/hrm_backend.git"

          echo "=== Configure Git SSH Key ==="
          export GIT_SSH_COMMAND="ssh -i ~/.ssh/hrm_key -o StrictHostKeyChecking=no"

          echo "=== Check repo exists ==="
          if [ ! -d "$REPO_DIR/.git" ]; then
            echo "Repo not found. Cloning fresh..."
            mkdir -p /root/projects/backend
            cd /root/projects/backend
            git clone $REPO_URL
          else
            echo "Repo exists. Cleaning and pulling latest code..."
            cd $REPO_DIR
            git reset --hard HEAD
            git clean -fd
            git pull origin main
          fi

          echo "=== Entering repo ==="
          cd $REPO_DIR

          echo "=== Copy .env.local â†’ .env ==="
          cp .env.local .env

          echo "=== Stopping existing container ==="
          docker compose down || true

          echo "=== Remove old backend image ==="
          docker images | grep "hrm_backend-backend" | awk '{print $3}' | xargs -r docker rmi -f || true

          echo "=== Building new backend image ==="
          docker compose build --no-cache

          echo "=== Starting new backend container ==="
          docker compose up -d

          echo "=== DEPLOYMENT SUCCESS ==="
